version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/teamspeak-server
    steps:
      - checkout
      - run:
          name: Install AWS CLI and Deploy Cloudformation
          command: |
            sudo apt-get update
            sudo apt-get install -y python2 python2-dev curl
            curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
            sudo python2 get-pip.py
            sudo pip2 install --upgrade awscli
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region us-east-1  # Set your preferred region
      - run: ./deploy.sh
